export { default } from "next-auth/middleware";

export const config = {
  matcher: [
    "/dashboard/:path*",
    "/wardrobe/:path*",
    "/outfits/:path*",
    "/profile/:path*",
    "/chat/:path*",
    "/sustainability/:path*",
    "/packing/:path*",
    "/calendar/:path*",
    "/capsule/:path*",
    "/history/:path*",
    "/api/wardrobe/:path*",
    "/api/upload-clothing/:path*",
    "/api/generate-outfit/:path*",
    "/api/outfit-of-the-day/:path*",
    "/api/feedback/:path*",
    "/api/profile/:path*",
    "/api/chat-stylist/:path*",
    "/api/chat-sessions/:path*",
    "/api/sustainability/:path*",
    "/api/packing/:path*",
    "/api/capsule/:path*",
    "/api/outfit-plan/:path*",
    "/api/skin-tone/:path*",
    "/api/outfit-history/:path*",
    "/api/cost-summary/:path*",
    "/api/google-calendar/:path*",
    "/wishlist",
    "/wishlist/:path*",
    "/api/wishlist/:path*",
  ],
};
